//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedDate
    {
        public int ed_id { get; set; }
        public Nullable<int> ed_event_id { get; set; }
        public Nullable<int> ed_event_type { get; set; }
        public Nullable<System.DateTime> ed_date { get; set; }
        public int ed_settings { get; set; }
        public int TimezoneOffsetInMinutes { get; set; }
    
        public virtual PlayingDatesSetting PlayingDatesSetting { get; set; }
    }
}
