//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubLeagueParticipant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClubLeagueParticipant()
        {
            this.ScandinavianStandings = new HashSet<ScandinavianStanding>();
        }
    
        public int Id { get; set; }
        public int ClubLeagueId { get; set; }
        public int ParticipantId { get; set; }
        public Nullable<int> Standing { get; set; }
        public Nullable<bool> IsFeePaid { get; set; }
        public int PoolOrder { get; set; }
        public bool IsConfirmed { get; set; }
        public int PositionDifference { get; set; }
        public int Seed { get; set; }
    
        public virtual ClubLeague ClubLeague { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScandinavianStanding> ScandinavianStandings { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
