//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubLeagueInvitation
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> DoublePartner { get; set; }
        public int ClubLeagueId { get; set; }
        public System.DateTime DateCreatedUTC { get; set; }
        public int Status { get; set; }
        public bool WasLookingForPartner { get; set; }
    
        public virtual ClubLeague ClubLeague { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
