//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubLeaguePool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClubLeaguePool()
        {
            this.RoundRobinStandings = new HashSet<RoundRobinStanding>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClubLeagueId { get; set; }
        public int PoolOrder { get; set; }
        public Nullable<int> PoolSize { get; set; }
    
        public virtual ClubLeague ClubLeague { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinStanding> RoundRobinStandings { get; set; }
    }
}
