//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubLeague
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClubLeague()
        {
            this.ClubLeagueInvitations = new HashSet<ClubLeagueInvitation>();
            this.ClubLeagueAdmins = new HashSet<ClubLeagueAdmin>();
            this.ScandinavianStandings = new HashSet<ScandinavianStanding>();
            this.ClubLeagueParticipants = new HashSet<ClubLeagueParticipant>();
            this.ClubLeaguePools = new HashSet<ClubLeaguePool>();
            this.ClubLeagueToRankingLevels = new HashSet<ClubLeagueToRankingLevel>();
            this.RoundRobinMatchPointSettings = new HashSet<RoundRobinMatchPointSetting>();
            this.RoundRobinRuleSettings = new HashSet<RoundRobinRuleSetting>();
        }
    
        public int lad_id { get; set; }
        public string lad_name { get; set; }
        public int lad_initiator_id { get; set; }
        public int lad_location_id { get; set; }
        public int lad_state { get; set; }
        public System.DateTime lad_start_date { get; set; }
        public System.DateTime lad_end_time { get; set; }
        public System.DateTime lad_closing_date { get; set; }
        public Nullable<int> lad_payment_type { get; set; }
        public Nullable<decimal> lad_payment_fee { get; set; }
        public Nullable<int> lad_payment_currency { get; set; }
        public string lad_info { get; set; }
        public int lad_players_per_pool { get; set; }
        public Nullable<int> lad_weekly_players_transfer { get; set; }
        public int lad_sport { get; set; }
        public int lad_lid { get; set; }
        public int lad_rankingtype { get; set; }
        public int lad_round { get; set; }
        public string lad_paypal_account { get; set; }
        public int lad_class { get; set; }
        public bool bl_scandinavian { get; set; }
        public Nullable<System.DateTime> lad_fixed_date { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int NoShowMovement { get; set; }
        public Nullable<int> SeedRankingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueInvitation> ClubLeagueInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueAdmin> ClubLeagueAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScandinavianStanding> ScandinavianStandings { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual Place Place { get; set; }
        public virtual Player Player { get; set; }
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueParticipant> ClubLeagueParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeaguePool> ClubLeaguePools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueToRankingLevel> ClubLeagueToRankingLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinMatchPointSetting> RoundRobinMatchPointSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinRuleSetting> RoundRobinRuleSettings { get; set; }
    }
}
