//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationHistory
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Country { get; set; }
        public string Sport { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public int Status { get; set; }
        public string SourceId { get; set; }
        public string ClientSecret { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
