//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawMovement
    {
        public int Id { get; set; }
        public int FromDrawId { get; set; }
        public int ToDrawId { get; set; }
        public int FromPosition { get; set; }
        public int ToPosition { get; set; }
    
        public virtual TournamentDraw TournamentDraw { get; set; }
        public virtual TournamentDraw TournamentDraw1 { get; set; }
    }
}
