//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventPoint()
        {
            this.EventToRankingPoints = new HashSet<EventToRankingPoint>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PrivateChallengeId { get; set; }
        public Nullable<int> ClubLeagueId { get; set; }
        public Nullable<int> TournamentClassId { get; set; }
        public Nullable<int> TeamMatchId { get; set; }
        public Nullable<int> TeamMatchNumber { get; set; }
        public string EventName { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> DoubleId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<int> ParticipantTypeId { get; set; }
        public int RankingId { get; set; }
        public int MatchTypeId { get; set; }
        public int AgeGroup { get; set; }
        public Nullable<int> Standing { get; set; }
        public Nullable<int> StandingTo { get; set; }
        public decimal Points { get; set; }
        public System.DateTime DateRankingStartUTC { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsFakePlayer { get; set; }
        public Nullable<int> EventParticipantId { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Player Player { get; set; }
        public virtual RankingType RankingType { get; set; }
        public virtual Double Double { get; set; }
        public virtual EventParticipant EventParticipant { get; set; }
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventToRankingPoint> EventToRankingPoints { get; set; }
    }
}
