//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int img_id { get; set; }
        public Nullable<int> img_event_player_id { get; set; }
        public int img_type { get; set; }
        public string img_path { get; set; }
    }
}
