//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Challenges = new HashSet<Challenge>();
            this.MatchParticipants = new HashSet<MatchParticipant>();
            this.MatchScores = new HashSet<MatchScore>();
        }
    
        public int m_id { get; set; }
        public int m_participant1 { get; set; }
        public int m_participant2 { get; set; }
        public System.DateTime m_date { get; set; }
        public Nullable<int> m_place { get; set; }
        public Nullable<int> m_result1 { get; set; }
        public Nullable<int> m_result2 { get; set; }
        public bool m_active { get; set; }
        public Nullable<int> m_winner { get; set; }
        public int m_eventtype { get; set; }
        public int m_sport { get; set; }
        public int m_round { get; set; }
        public Nullable<int> m_rankingtype { get; set; }
        public int m_class { get; set; }
        public System.DateTime DateModifiedUTC { get; set; }
        public Nullable<System.DateTime> DateConfirmedUTC { get; set; }
        public Nullable<int> Cancellation { get; set; }
        public Nullable<int> CancelledMatchParticipantId { get; set; }
        public Nullable<System.DateTime> DateReminderSentUTC { get; set; }
        public int PlayingDateUTCOffsetInMinutes { get; set; }
        public bool IsLive { get; set; }
        public Nullable<System.DateTime> DateRefereeStartedUTC { get; set; }
        public Nullable<System.DateTime> DateFinishedUTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Challenge> Challenges { get; set; }
        public virtual MatchParticipant MatchParticipant { get; set; }
        public virtual Place Place { get; set; }
        public virtual Sport Sport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchParticipant> MatchParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchScore> MatchScores { get; set; }
    }
}
