//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchParticipant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchParticipant()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public int MatchId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> DoubleId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<int> ParticipantTypeId { get; set; }
        public Nullable<int> Result { get; set; }
        public int ParticipantStatus { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public Nullable<int> EventParticipantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual Double Double { get; set; }
        public virtual EventParticipant EventParticipant { get; set; }
    }
}
