//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchScore
    {
        public int Id { get; set; }
        public int Score1 { get; set; }
        public int Score2 { get; set; }
        public int MatchId { get; set; }
        public int Duration { get; set; }
        public Nullable<int> LoserTiebreak { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
