//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.Players = new HashSet<Player>();
            this.FederationClubs = new HashSet<FederationClub>();
            this.FederationClubs1 = new HashSet<FederationClub>();
            this.OrganizationAdmins = new HashSet<OrganizationAdmin>();
            this.OrganisationRankings = new HashSet<OrganisationRanking>();
            this.ParticipantLicenses = new HashSet<ParticipantLicens>();
            this.TeamDetails = new HashSet<TeamDetail>();
            this.TeamLeagueTeams = new HashSet<TeamLeagueTeam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Information { get; set; }
        public string Venue { get; set; }
        public int OrganisationType { get; set; }
        public Nullable<int> InitiatorId { get; set; }
        public Nullable<decimal> DonationsPaid { get; set; }
        public Nullable<System.DateTime> LastDonationPaymentDate { get; set; }
        public string PayPalAccount { get; set; }
        public System.DateTime DateCreatedUTC { get; set; }
        public string Book247AccessKey { get; set; }
        public string Book247AccountName { get; set; }
        public string Book247AccountSubdomain { get; set; }
        public Nullable<System.DateTime> Book247IntegrationDate { get; set; }
        public bool SupportsClubMembers { get; set; }
    
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FederationClub> FederationClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FederationClub> FederationClubs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationAdmin> OrganizationAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationRanking> OrganisationRankings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantLicens> ParticipantLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamDetail> TeamDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueTeam> TeamLeagueTeams { get; set; }
    }
}
