//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantLicens
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int OrganisationId { get; set; }
        public bool HasValidLicense { get; set; }
        public int LicenseStatus { get; set; }
        public string MembershipName { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
