//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInfo()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int pi_id { get; set; }
        public System.DateTime pi_birth { get; set; }
        public Nullable<int> pi_gender { get; set; }
        public int pi_country { get; set; }
        public int pi_favouritesport { get; set; }
        public bool pi_birth_v { get; set; }
        public bool pi_email_v { get; set; }
        public int DominantHand { get; set; }
        public int Backhand { get; set; }
        public string FacebookProfile { get; set; }
        public string TwitterProfile { get; set; }
        public string WebSite { get; set; }
        public string Sponsor { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Sport Sport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
