//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.ClubLeagues = new HashSet<ClubLeague>();
            this.ClubLeagueAdmins = new HashSet<ClubLeagueAdmin>();
            this.ClubLeagueInvitations = new HashSet<ClubLeagueInvitation>();
            this.ClubLeagueInvitations1 = new HashSet<ClubLeagueInvitation>();
            this.ChatParticipants = new HashSet<ChatParticipant>();
            this.DonationHistories = new HashSet<DonationHistory>();
            this.EventInitiators = new HashSet<EventInitiator>();
            this.OrganizationAdmins = new HashSet<OrganizationAdmin>();
            this.PlayerRacquets = new HashSet<PlayerRacquet>();
            this.PlayerShoes = new HashSet<PlayerShoe>();
            this.TeamLeagueAdmins = new HashSet<TeamLeagueAdmin>();
            this.TournamentAdmins = new HashSet<TournamentAdmin>();
            this.TournamentInvitations = new HashSet<TournamentInvitation>();
            this.TournamentInvitations1 = new HashSet<TournamentInvitation>();
            this.Doubles = new HashSet<Double>();
            this.Doubles1 = new HashSet<Double>();
            this.EventPoints = new HashSet<EventPoint>();
            this.EventStandings = new HashSet<EventStanding>();
            this.MatchParticipants = new HashSet<MatchParticipant>();
            this.PlayerNotifications = new HashSet<PlayerNotification>();
            this.RoundRobinStandings = new HashSet<RoundRobinStanding>();
            this.TeamLeagues = new HashSet<TeamLeague>();
            this.TeamLeagueTeams = new HashSet<TeamLeagueTeam>();
            this.TeamMatchMatches = new HashSet<TeamMatchMatch>();
            this.TeamParticipants = new HashSet<TeamParticipant>();
            this.Tournaments = new HashSet<Tournament>();
        }
    
        public int p_id { get; set; }
        public int p_info { get; set; }
        public Nullable<int> p_user { get; set; }
        public Nullable<int> p_class { get; set; }
        public int LanguageId { get; set; }
        public bool p_receive_emails { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> HomeClubId { get; set; }
        public string ImagePath { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public Nullable<int> SSOUserId { get; set; }
        public bool AutoSignUp { get; set; }
        public bool AutoSignUpTournament { get; set; }
        public int PreferredUTCOffsetInMinutes { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SPIN { get; set; }
        public string RankedinId { get; set; }
        public bool IsFake { get; set; }
        public int ParticipantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeague> ClubLeagues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueAdmin> ClubLeagueAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueInvitation> ClubLeagueInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueInvitation> ClubLeagueInvitations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatParticipant> ChatParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationHistory> DonationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventInitiator> EventInitiators { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationAdmin> OrganizationAdmins { get; set; }
        public virtual Organisation Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerRacquet> PlayerRacquets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerShoe> PlayerShoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueAdmin> TeamLeagueAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentAdmin> TournamentAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentInvitation> TournamentInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentInvitation> TournamentInvitations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Double> Doubles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Double> Doubles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPoint> EventPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventStanding> EventStandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchParticipant> MatchParticipants { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerNotification> PlayerNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinStanding> RoundRobinStandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeague> TeamLeagues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueTeam> TeamLeagueTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchMatch> TeamMatchMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamParticipant> TeamParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournament> Tournaments { get; set; }
    }
}
