//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayingDatesSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayingDatesSetting()
        {
            this.AllowedDates = new HashSet<AllowedDate>();
        }
    
        public int ed_id { get; set; }
        public Nullable<System.DateTime> ed_start { get; set; }
        public Nullable<System.DateTime> ed_end { get; set; }
        public Nullable<int> ed_duration { get; set; }
        public Nullable<int> ed_maxcourts { get; set; }
        public Nullable<int> ed_minbreak { get; set; }
        public Nullable<int> MaxPlayerMatchesPerDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllowedDate> AllowedDates { get; set; }
    }
}
