//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rankedin_testEntities : DbContext
    {
        public rankedin_testEntities()
            : base("name=rankedin_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClubLeague> ClubLeagues { get; set; }
        public virtual DbSet<ClubLeagueAdmin> ClubLeagueAdmins { get; set; }
        public virtual DbSet<ClubLeagueInvitation> ClubLeagueInvitations { get; set; }
        public virtual DbSet<ClubLeagueParticipant> ClubLeagueParticipants { get; set; }
        public virtual DbSet<ClubLeaguePool> ClubLeaguePools { get; set; }
        public virtual DbSet<ScandinavianStanding> ScandinavianStandings { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Age> Ages { get; set; }
        public virtual DbSet<AgeGroupMap> AgeGroupMaps { get; set; }
        public virtual DbSet<AgeGroup> AgeGroups { get; set; }
        public virtual DbSet<AgeGroupToSportMap> AgeGroupToSportMaps { get; set; }
        public virtual DbSet<AllowedDate> AllowedDates { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ChatParticipant> ChatParticipants { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DonationHistory> DonationHistories { get; set; }
        public virtual DbSet<EventInitiator> EventInitiators { get; set; }
        public virtual DbSet<EventRole> EventRoles { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<ParticipantType> ParticipantTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfoes { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerNotification> PlayerNotifications { get; set; }
        public virtual DbSet<PlayerRacquet> PlayerRacquets { get; set; }
        public virtual DbSet<PlayerShoe> PlayerShoes { get; set; }
        public virtual DbSet<PlayersImportQueue> PlayersImportQueues { get; set; }
        public virtual DbSet<Racquet> Racquets { get; set; }
        public virtual DbSet<RankingType> RankingTypes { get; set; }
        public virtual DbSet<RoundRobinMatchPointSetting> RoundRobinMatchPointSettings { get; set; }
        public virtual DbSet<RoundRobinRule> RoundRobinRules { get; set; }
        public virtual DbSet<RoundRobinRuleSetting> RoundRobinRuleSettings { get; set; }
        public virtual DbSet<RoundRobinStanding> RoundRobinStandings { get; set; }
        public virtual DbSet<ScoreRule> ScoreRules { get; set; }
        public virtual DbSet<ScoreRuleType> ScoreRuleTypes { get; set; }
        public virtual DbSet<Shoe> Shoes { get; set; }
        public virtual DbSet<SponsorLogo> SponsorLogos { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_FacebookCredentials> webpages_FacebookCredentials { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual DbSet<MatchParticipant> MatchParticipants { get; set; }
        public virtual DbSet<MatchScore> MatchScores { get; set; }
        public virtual DbSet<FederationClub> FederationClubs { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<OrganizationAdmin> OrganizationAdmins { get; set; }
        public virtual DbSet<Double> Doubles { get; set; }
        public virtual DbSet<EventParticipant> EventParticipants { get; set; }
        public virtual DbSet<ParticipantLicens> ParticipantLicenses { get; set; }
        public virtual DbSet<ParticipantMap> ParticipantMaps { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<ParticipantStatistic> ParticipantStatistics { get; set; }
        public virtual DbSet<TeamDetail> TeamDetails { get; set; }
        public virtual DbSet<ClubLeagueToRankingLevel> ClubLeagueToRankingLevels { get; set; }
        public virtual DbSet<EventPoint> EventPoints { get; set; }
        public virtual DbSet<EventStanding> EventStandings { get; set; }
        public virtual DbSet<EventToRankingPoint> EventToRankingPoints { get; set; }
        public virtual DbSet<OrganisationRanking> OrganisationRankings { get; set; }
        public virtual DbSet<RankingEvent> RankingEvents { get; set; }
        public virtual DbSet<RankingLevelPoint> RankingLevelPoints { get; set; }
        public virtual DbSet<RankingLevel> RankingLevels { get; set; }
        public virtual DbSet<RankingParticipant> RankingParticipants { get; set; }
        public virtual DbSet<RankingPoint> RankingPoints { get; set; }
        public virtual DbSet<RankingSetting> RankingSettings { get; set; }
        public virtual DbSet<TournamentClassToRankingLevel> TournamentClassToRankingLevels { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<DivisionMatchSetting> DivisionMatchSettings { get; set; }
        public virtual DbSet<TeamAdmin> TeamAdmins { get; set; }
        public virtual DbSet<TeamLeagueAdmin> TeamLeagueAdmins { get; set; }
        public virtual DbSet<TeamLeagueDivisionDay> TeamLeagueDivisionDays { get; set; }
        public virtual DbSet<TeamLeagueDivision> TeamLeagueDivisions { get; set; }
        public virtual DbSet<TeamLeagueNonPlayingDate> TeamLeagueNonPlayingDates { get; set; }
        public virtual DbSet<TeamLeaguePool> TeamLeaguePools { get; set; }
        public virtual DbSet<TeamLeagueRankingLevelPoint> TeamLeagueRankingLevelPoints { get; set; }
        public virtual DbSet<TeamLeagueRankingLevel> TeamLeagueRankingLevels { get; set; }
        public virtual DbSet<TeamLeagueRegion> TeamLeagueRegions { get; set; }
        public virtual DbSet<TeamLeague> TeamLeagues { get; set; }
        public virtual DbSet<TeamLeagueTeamLineup> TeamLeagueTeamLineups { get; set; }
        public virtual DbSet<TeamLeagueTeam> TeamLeagueTeams { get; set; }
        public virtual DbSet<TeamMatch> TeamMatches { get; set; }
        public virtual DbSet<TeamMatchMatch> TeamMatchMatches { get; set; }
        public virtual DbSet<TeamMatchTeam> TeamMatchTeams { get; set; }
        public virtual DbSet<TeamParticipant> TeamParticipants { get; set; }
        public virtual DbSet<TeamParticipantType> TeamParticipantTypes { get; set; }
        public virtual DbSet<DrawMovement> DrawMovements { get; set; }
        public virtual DbSet<DrawParticipant> DrawParticipants { get; set; }
        public virtual DbSet<PlayingDatesSetting> PlayingDatesSettings { get; set; }
        public virtual DbSet<PSATournamentDetail> PSATournamentDetails { get; set; }
        public virtual DbSet<TeamMatchSetting> TeamMatchSettings { get; set; }
        public virtual DbSet<Tournament> Tournaments { get; set; }
        public virtual DbSet<TournamentAdmin> TournamentAdmins { get; set; }
        public virtual DbSet<TournamentCourt> TournamentCourts { get; set; }
        public virtual DbSet<TournamentDraw> TournamentDraws { get; set; }
        public virtual DbSet<TournamentEvent> TournamentEvents { get; set; }
        public virtual DbSet<TournamentInvitation> TournamentInvitations { get; set; }
        public virtual DbSet<TournamentMatch> TournamentMatches { get; set; }
        public virtual DbSet<TournamentPlayer> TournamentPlayers { get; set; }
        public virtual DbSet<PlayerAgeGroup> PlayerAgeGroups { get; set; }
        public virtual DbSet<RankingPlayerAgeGroup> RankingPlayerAgeGroups { get; set; }
        public virtual DbSet<vEvent> vEvents { get; set; }
        public virtual DbSet<vParticipant> vParticipants { get; set; }
        public virtual DbSet<RankingEventsForApproval> RankingEventsForApprovals { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
