//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RankingPoint()
        {
            this.EventToRankingPoints = new HashSet<EventToRankingPoint>();
        }
    
        public int Id { get; set; }
        public int RankingParticipantId { get; set; }
        public int AgeGroup { get; set; }
        public System.DateTime RankingDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
        public int Standing { get; set; }
        public decimal Points { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int ParticipantAge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventToRankingPoint> EventToRankingPoints { get; set; }
        public virtual RankingParticipant RankingParticipant { get; set; }
    }
}
