//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RankingLevel()
        {
            this.ClubLeagueToRankingLevels = new HashSet<ClubLeagueToRankingLevel>();
            this.RankingLevelPoints = new HashSet<RankingLevelPoint>();
            this.TournamentClassToRankingLevels = new HashSet<TournamentClassToRankingLevel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int OrganisationRankingId { get; set; }
        public bool IsActive { get; set; }
        public int RankingEventTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubLeagueToRankingLevel> ClubLeagueToRankingLevels { get; set; }
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RankingLevelPoint> RankingLevelPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentClassToRankingLevel> TournamentClassToRankingLevels { get; set; }
    }
}
