//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingParticipant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RankingParticipant()
        {
            this.RankingPoints = new HashSet<RankingPoint>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public int ParticipantTypeId { get; set; }
        public int MatchTypeId { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public System.DateTime StartDate { get; set; }
        public int OrganisationRankingId { get; set; }
    
        public virtual ParticipantType ParticipantType { get; set; }
        public virtual RankingType RankingType { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RankingPoint> RankingPoints { get; set; }
    }
}
