//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingEvent
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public int EventType { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> TeamLeagueId { get; set; }
        public int OrganisationRankingId { get; set; }
    
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
    }
}
