//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingSetting
    {
        public int rs_id { get; set; }
        public int rs_type { get; set; }
        public decimal rs_value { get; set; }
        public int OrganisationRankingId { get; set; }
    }
}
