//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingEventsForApproval
    {
        public int Type { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public System.DateTime StartDate { get; set; }
        public int RankingId { get; set; }
        public string RankingName { get; set; }
        public string CountryShort { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> EventId { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public Nullable<int> LevelId { get; set; }
    }
}
