//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundRobinMatchPointSetting
    {
        public int Id { get; set; }
        public int WinPoints { get; set; }
        public int DrawPoints { get; set; }
        public int LosePoints { get; set; }
        public bool LoserPointsForWalkOver { get; set; }
        public Nullable<int> TournamentClassId { get; set; }
        public Nullable<int> ClubLeagueId { get; set; }
        public Nullable<int> TeamLeagueId { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public bool IsForTeamMatches { get; set; }
    
        public virtual ClubLeague ClubLeague { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
        public virtual TournamentEvent TournamentEvent { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
