//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundRobinStanding
    {
        public int Id { get; set; }
        public int Standing { get; set; }
        public int Points { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> DoubleId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<int> TournamentDrawId { get; set; }
        public Nullable<int> ClubLeaguePoolId { get; set; }
        public Nullable<int> TeamLeaguePoolId { get; set; }
        public Nullable<int> EventParticipantId { get; set; }
    
        public virtual ClubLeaguePool ClubLeaguePool { get; set; }
        public virtual Player Player { get; set; }
        public virtual Double Double { get; set; }
        public virtual EventParticipant EventParticipant { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual TeamLeaguePool TeamLeaguePool { get; set; }
        public virtual TournamentDraw TournamentDraw { get; set; }
    }
}
