//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreRule
    {
        public int Id { get; set; }
        public int SportId { get; set; }
        public int ScoreRuleTypeId { get; set; }
        public Nullable<int> RankingTypeId { get; set; }
        public int GamesCount { get; set; }
        public bool AskForSuperTieBreak { get; set; }
        public bool AskForGamesCount { get; set; }
        public bool AskForGamePoints { get; set; }
        public Nullable<int> BreakInSec { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual RankingType RankingType { get; set; }
        public virtual ScoreRuleType ScoreRuleType { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
