//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeagueRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamLeagueRegion()
        {
            this.TeamLeaguePools = new HashSet<TeamLeaguePool>();
        }
    
        public int Id { get; set; }
        public int TeamLeagueId { get; set; }
        public string Name { get; set; }
        public int RegionOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeaguePool> TeamLeaguePools { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
    }
}
