//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMatchTeam
    {
        public int Id { get; set; }
        public int TeamMatchId { get; set; }
        public Nullable<int> EventParticipantId { get; set; }
        public Nullable<int> TeamLeagueTeamId { get; set; }
        public int Result { get; set; }
        public int TeamMatchSide { get; set; }
        public Nullable<int> LineupInitiatorId { get; set; }
        public Nullable<System.DateTime> LineupDate { get; set; }
    
        public virtual EventParticipant EventParticipant { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual TeamMatch TeamMatch { get; set; }
    }
}
