//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeagueDivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamLeagueDivision()
        {
            this.DivisionMatchSettings = new HashSet<DivisionMatchSetting>();
            this.TeamLeagueDivisionDays = new HashSet<TeamLeagueDivisionDay>();
            this.TeamLeaguePools = new HashSet<TeamLeaguePool>();
            this.TeamLeagueRankingLevelPoints = new HashSet<TeamLeagueRankingLevelPoint>();
        }
    
        public int Id { get; set; }
        public int TeamLeagueId { get; set; }
        public string Name { get; set; }
        public int TeamMatchesPerDay { get; set; }
        public int DivisionOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionMatchSetting> DivisionMatchSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueDivisionDay> TeamLeagueDivisionDays { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeaguePool> TeamLeaguePools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueRankingLevelPoint> TeamLeagueRankingLevelPoints { get; set; }
    }
}
