//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeagueTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamLeagueTeam()
        {
            this.TeamLeagueTeamLineups = new HashSet<TeamLeagueTeamLineup>();
            this.TeamParticipants = new HashSet<TeamParticipant>();
        }
    
        public int Id { get; set; }
        public int InitiatorId { get; set; }
        public int TeamLeagueId { get; set; }
        public int TeamLeaguePoolId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<int> HomeClubId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual TeamLeaguePool TeamLeaguePool { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueTeamLineup> TeamLeagueTeamLineups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamParticipant> TeamParticipants { get; set; }
    }
}
