//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeagueRankingLevelPoint
    {
        public int Id { get; set; }
        public int RankingLevelId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public int PlayerLineup { get; set; }
        public decimal WinnerPoints { get; set; }
        public decimal LoserPoints { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual TeamLeagueDivision TeamLeagueDivision { get; set; }
        public virtual TeamLeagueRankingLevel TeamLeagueRankingLevel { get; set; }
    }
}
