//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamAdmin
    {
        public int Id { get; set; }
        public int TeamLeagueTeamId { get; set; }
        public int ParticipantId { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
    }
}
