//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamMatch()
        {
            this.TeamLeagueTeamLineups = new HashSet<TeamLeagueTeamLineup>();
            this.TeamMatchMatches = new HashSet<TeamMatchMatch>();
            this.TeamMatchTeams = new HashSet<TeamMatchTeam>();
        }
    
        public int Id { get; set; }
        public int TeamLeaguePoolId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public int TeamMatchState { get; set; }
        public Nullable<int> WinnerTeamId { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public int Round { get; set; }
        public int CancellationEvent { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual TeamLeaguePool TeamLeaguePool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueTeamLineup> TeamLeagueTeamLineups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchMatch> TeamMatchMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchTeam> TeamMatchTeams { get; set; }
    }
}
