//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMatchMatch
    {
        public int Id { get; set; }
        public int TeamMatchId { get; set; }
        public int ChallengeId { get; set; }
        public int MatchOrder { get; set; }
        public Nullable<int> TeamLeagueTeamLineupId { get; set; }
        public int TeamMatchSide { get; set; }
        public Nullable<int> ResultInitiatorId { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Player Player { get; set; }
        public virtual TeamMatch TeamMatch { get; set; }
    }
}
