//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMatchSetting
    {
        public int Id { get; set; }
        public int TournamentClassId { get; set; }
        public int MatchType { get; set; }
        public int MatchesCount { get; set; }
        public int MatchOrder { get; set; }
    
        public virtual TournamentEvent TournamentEvent { get; set; }
    }
}
