//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeaguePool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamLeaguePool()
        {
            this.RoundRobinStandings = new HashSet<RoundRobinStanding>();
            this.TeamDetails = new HashSet<TeamDetail>();
            this.TeamLeagueTeams = new HashSet<TeamLeagueTeam>();
            this.TeamMatches = new HashSet<TeamMatch>();
        }
    
        public int Id { get; set; }
        public int TeamLeagueId { get; set; }
        public int TeamLeagueDivisionId { get; set; }
        public int TeamLeagueRegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinStanding> RoundRobinStandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamDetail> TeamDetails { get; set; }
        public virtual TeamLeagueDivision TeamLeagueDivision { get; set; }
        public virtual TeamLeague TeamLeague { get; set; }
        public virtual TeamLeagueRegion TeamLeagueRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLeagueTeam> TeamLeagueTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatch> TeamMatches { get; set; }
    }
}
