//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentDraw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentDraw()
        {
            this.RoundRobinStandings = new HashSet<RoundRobinStanding>();
            this.DrawMovements = new HashSet<DrawMovement>();
            this.DrawMovements1 = new HashSet<DrawMovement>();
            this.DrawParticipants = new HashSet<DrawParticipant>();
            this.TournamentMatches = new HashSet<TournamentMatch>();
        }
    
        public int td_id { get; set; }
        public int td_drawtype { get; set; }
        public Nullable<int> td_size { get; set; }
        public Nullable<bool> td_qualification { get; set; }
        public string td_name { get; set; }
        public int td_event { get; set; }
        public Nullable<bool> IsDrawPublished { get; set; }
        public int Stage { get; set; }
        public int Strength { get; set; }
        public Nullable<int> OutputSize { get; set; }
        public int ConsolationsCount { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Playoffs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinStanding> RoundRobinStandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawMovement> DrawMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawMovement> DrawMovements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawParticipant> DrawParticipants { get; set; }
        public virtual TournamentEvent TournamentEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentMatch> TournamentMatches { get; set; }
    }
}
