//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentMatch
    {
        public int Id { get; set; }
        public Nullable<int> CourtId { get; set; }
        public Nullable<int> NoScheduleCourtPosition { get; set; }
        public int ChallengeId { get; set; }
        public int TournamentDrawId { get; set; }
        public bool IsActive { get; set; }
        public int Round { get; set; }
        public int MatchOrder { get; set; }
        public int TournamentMatchState { get; set; }
        public Nullable<int> WinnerPlace { get; set; }
        public int Consolation { get; set; }
        public bool IsMatchScheduled { get; set; }
        public Nullable<int> MasterId { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual TournamentCourt TournamentCourt { get; set; }
        public virtual TournamentDraw TournamentDraw { get; set; }
    }
}
