//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.RoundRobinMatchPointSettings = new HashSet<RoundRobinMatchPointSetting>();
            this.RoundRobinRuleSettings = new HashSet<RoundRobinRuleSetting>();
            this.PSATournamentDetails = new HashSet<PSATournamentDetail>();
            this.TournamentAdmins = new HashSet<TournamentAdmin>();
            this.TournamentInvitations = new HashSet<TournamentInvitation>();
            this.TournamentCourts = new HashSet<TournamentCourt>();
            this.TournamentEvents = new HashSet<TournamentEvent>();
        }
    
        public int t_id { get; set; }
        public int t_eventstate { get; set; }
        public int t_tournametstate { get; set; }
        public System.DateTime t_initiated { get; set; }
        public System.DateTime t_startdate { get; set; }
        public System.DateTime t_closingdate { get; set; }
        public System.DateTime t_enddate { get; set; }
        public string t_paypalacc { get; set; }
        public Nullable<int> t_payment_type { get; set; }
        public Nullable<int> t_payment_currency { get; set; }
        public Nullable<decimal> t_payment_fee { get; set; }
        public string t_regulations { get; set; }
        public string t_name { get; set; }
        public int t_initiator { get; set; }
        public int t_sport { get; set; }
        public int PlaceId { get; set; }
        public bool ShowRefereeCodes { get; set; }
        public Nullable<int> SeedRankingId { get; set; }
        public bool IsStreamingPlanned { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<int> UserFinished { get; set; }
        public bool AreMatchesPublished { get; set; }
        public Nullable<int> TeamMatchesScoringType { get; set; }
        public bool AreStandingsGenerated { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinMatchPointSetting> RoundRobinMatchPointSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinRuleSetting> RoundRobinRuleSettings { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual OrganisationRanking OrganisationRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSATournamentDetail> PSATournamentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentAdmin> TournamentAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentInvitation> TournamentInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentCourt> TournamentCourts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentEvent> TournamentEvents { get; set; }
    }
}
