//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentCourt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentCourt()
        {
            this.TournamentMatches = new HashSet<TournamentMatch>();
        }
    
        public int tc_id { get; set; }
        public string tc_name { get; set; }
        public int tc_location { get; set; }
        public int tc_tournament { get; set; }
        public string tc_description { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentMatch> TournamentMatches { get; set; }
    }
}
