//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentEvent()
        {
            this.RoundRobinMatchPointSettings = new HashSet<RoundRobinMatchPointSetting>();
            this.RoundRobinRuleSettings = new HashSet<RoundRobinRuleSetting>();
            this.TournamentClassToRankingLevels = new HashSet<TournamentClassToRankingLevel>();
            this.TeamMatchSettings = new HashSet<TeamMatchSetting>();
            this.TournamentDraws = new HashSet<TournamentDraw>();
            this.TournamentInvitations = new HashSet<TournamentInvitation>();
            this.TournamentPlayers = new HashSet<TournamentPlayer>();
        }
    
        public int te_id { get; set; }
        public int te_tournament { get; set; }
        public int te_rankingtype { get; set; }
        public string te_name { get; set; }
        public int tc_maindrawsize { get; set; }
        public int tc_drawtype { get; set; }
        public int RegeneratedCount { get; set; }
        public int State { get; set; }
        public int AgeGroup { get; set; }
        public int ScheduleOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinMatchPointSetting> RoundRobinMatchPointSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundRobinRuleSetting> RoundRobinRuleSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentClassToRankingLevel> TournamentClassToRankingLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchSetting> TeamMatchSettings { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentDraw> TournamentDraws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentInvitation> TournamentInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentPlayer> TournamentPlayers { get; set; }
    }
}
