//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int tr_id { get; set; }
        public int tr_language { get; set; }
        public string tr_key { get; set; }
        public string tr_text { get; set; }
        public string tr_description { get; set; }
        public System.DateTime tr_last_change { get; set; }
        public bool Translated { get; set; }
    }
}
