//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEvent
    {
        public int Id { get; set; }
        public int EventType { get; set; }
        public int EventState { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CloseSignInDate { get; set; }
        public string Name { get; set; }
        public int Sport { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    }
}
