//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerV3.RankedinTestDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vParticipant
    {
        public int ParticipantId { get; set; }
        public int ParticipantTypeId { get; set; }
        public int Id { get; set; }
        public int Info { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public int LanguageId { get; set; }
        public bool ReceiveEmails { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> HomeClubId { get; set; }
        public string ImagePath { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public Nullable<int> SSOUserId { get; set; }
        public bool AutoSignUp { get; set; }
        public bool AutoSignUpTournament { get; set; }
        public int PreferredUTCOffsetInMinutes { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SPIN { get; set; }
        public string RankedinId { get; set; }
        public bool IsFake { get; set; }
    }
}
